-------------------------------
-- DROP ALL DROPPABLE THINGS --
-------------------------------


DROP TABLE MATERIAL;
DROP TABLE PRODUCT_GROUP;
DROP TABLE UNIT_OF_MEASURE;

------------
-- CREATE --
------------


CREATE TABLE MATERIAL 
    ( 
     CODE VARCHAR2 (40)  NOT NULL , 
     SHORT_DESCRIPTION_EN VARCHAR2 (100) , 
     TYPE VARCHAR2 (10) , 
     UM_CODE VARCHAR2 (10) , 
     PRODUCT_GROUP_CODE VARCHAR2 (50) , 
     MACHINE_CODE VARCHAR2 (20) , 
     MAIN_PART_NUMBER VARCHAR2 (50) 
    ) 
    LOGGING 
;



ALTER TABLE MATERIAL 
    ADD CONSTRAINT MATERIAL_PK PRIMARY KEY ( CODE ) ;



CREATE TABLE PRODUCT_GROUP 
    ( 
     CODE VARCHAR2 (50)  NOT NULL , 
     DESCRIPTION VARCHAR2 (100) 
    ) 
    LOGGING 
;



ALTER TABLE PRODUCT_GROUP 
    ADD CONSTRAINT PRODUCT_GROUP_PK PRIMARY KEY ( CODE ) ;



CREATE TABLE UNIT_OF_MEASURE 
    ( 
     CODE VARCHAR2 (10)  NOT NULL , 
     TECH_CODE VARCHAR2 (10) , 
     DESCRIPTION VARCHAR2 (50) 
    ) 
    LOGGING 
;



ALTER TABLE UNIT_OF_MEASURE 
    ADD CONSTRAINT UNIT_OF_MEASURE_PK PRIMARY KEY ( CODE ) ;




ALTER TABLE MATERIAL 
    ADD CONSTRAINT MATERIAL_MACHINE_FK FOREIGN KEY 
    ( 
     MACHINE_CODE
    ) 
    REFERENCES MACHINE 
    ( 
     MACHINE_CODE
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE MATERIAL 
    ADD CONSTRAINT MATERIAL_PRODUCT_GROUP_FK FOREIGN KEY 
    ( 
     PRODUCT_GROUP_CODE
    ) 
    REFERENCES PRODUCT_GROUP 
    ( 
     CODE
    ) 
    ON DELETE CASCADE 
    NOT DEFERRABLE 
;


ALTER TABLE MATERIAL 
    ADD CONSTRAINT MATERIAL_UNIT_OF_MEASURE_FK FOREIGN KEY 
    ( 
     UM_CODE
    ) 
    REFERENCES UNIT_OF_MEASURE 
    ( 
     CODE
    ) 
    ON DELETE CASCADE 
    NOT DEFERRABLE 
;

