-------------------------------
-- DROP ALL DROPPABLE THINGS --
-------------------------------


DROP TABLE SAIPEM_FLAT_DATA;
DROP TABLE MATERIAL;
DROP TABLE PRODUCT_GROUP;
DROP TABLE UNIT_OF_MEASURE;
DROP TABLE MACHINE;
DROP TABLE MANUFACTURER;
DROP TABLE G_ROUP; -- "GROUP" is a reserved word
DROP TABLE SUBGROUP;

------------
-- CREATE --
------------

CREATE TABLE SAIPEM_FLAT_DATA 
    ( 
     CODE VARCHAR2 (40)  NOT NULL , 
     SHORT_DESCRIPTION_IT VARCHAR2 (100) , 
     SHORT_DESCRIPTION_EN VARCHAR2 (100) , 
     SHORT_DESCRIPTION_ES VARCHAR2 (100) , 
     TYPE VARCHAR2 (10) , 
     UM_CODE VARCHAR2 (10) , 
     UM_TECH_CODE VARCHAR2 (10) , 
     UM_DESCRIPTION VARCHAR2 (50) , 
     PG_CODE VARCHAR2 (50) , 
     PG_SHORT_DES_IT VARCHAR2 (40) , 
     PG_LONG_DES_IT VARCHAR2 (100) , 
     PG_SHORT_DES_EN VARCHAR2 (40) , 
     PG_LONG_DES_EN VARCHAR2 (100) , 
     PG_SHORT_DES_ES VARCHAR2 (40) , 
     PG_LONG_DES_ES VARCHAR2 (100) , 
     LAB VARCHAR2 (10) , 
     MACHINE_CODE VARCHAR2 (20) , 
     MAIN_PART_NUMBER VARCHAR2 (50) , 
     GROUP_CODE VARCHAR2 (10) , 
     SUBGROUP_CODE VARCHAR2 (10) , 
     MANUFACTURER_CODE VARCHAR2 (10) 
    ) 
    LOGGING 
;





