-------------------------------
-- DROP ALL DROPPABLE THINGS --
-------------------------------


DROP TABLE SAIPEM_FLAT_DATA;
DROP TABLE MATERIAL;
DROP TABLE PRODUCT_GROUP;
DROP TABLE UNIT_OF_MEASURE;
DROP TABLE MACHINE;
DROP TABLE SUBGROUP;
DROP TABLE G_ROUP; -- "GROUP" is a reserved word
DROP TABLE MANUFACTURER;

------------
-- CREATE --
------------

CREATE TABLE SAIPEM_FLAT_DATA 
    ( 
     CODE VARCHAR2 (40)  NOT NULL , 
     SHORT_DESCRIPTION_IT VARCHAR2 (100) , 
     SHORT_DESCRIPTION_EN VARCHAR2 (100) , 
     SHORT_DESCRIPTION_ES VARCHAR2 (100) , 
     TYPE VARCHAR2 (10) , 
     UM_CODE VARCHAR2 (10) , 
     UM_TECH_CODE VARCHAR2 (10) , 
     UM_DESCRIPTION VARCHAR2 (50) , 
     PG_CODE VARCHAR2 (50) , 
     PG_SHORT_DES_IT VARCHAR2 (40) , 
     PG_LONG_DES_IT VARCHAR2 (100) , 
     PG_SHORT_DES_EN VARCHAR2 (40) , 
     PG_LONG_DES_EN VARCHAR2 (100) , 
     PG_SHORT_DES_ES VARCHAR2 (40) , 
     PG_LONG_DES_ES VARCHAR2 (100) , 
     LAB VARCHAR2 (10) , 
     MACHINE_CODE VARCHAR2 (20) , 
     MAIN_PART_NUMBER VARCHAR2 (50) , 
     GROUP_CODE VARCHAR2 (10) , 
     SUBGROUP_CODE VARCHAR2 (10) , 
     MANUFACTURER_CODE VARCHAR2 (10) 
    ) 
    LOGGING 
;



------------
-- G_ROUP --
------------
CREATE TABLE G_ROUP 
    ( 
     GROUP_CODE VARCHAR2 (10)  NOT NULL , 
     DESCRIPTION_EN VARCHAR2 (100) , 
     DESCRIPTION_IT VARCHAR2 (100) 
    ) 
    LOGGING 
;

ALTER TABLE G_ROUP 
    ADD CONSTRAINT GROUP_PK PRIMARY KEY ( GROUP_CODE ) ;

    
    
--------------
-- SUBGROUP --
--------------
CREATE TABLE SUBGROUP 
    ( 
     GROUP_CODE VARCHAR2 (10)  NOT NULL , 
     SUBGROUP_CODE VARCHAR2 (10)  NOT NULL , 
     DESCRIPTION_EN VARCHAR2 (100) , 
     DESCRIPTION_IT VARCHAR2 (100) 
    ) 
    LOGGING 
;

ALTER TABLE SUBGROUP 
    ADD CONSTRAINT SUBGROUP_PK PRIMARY KEY ( GROUP_CODE, SUBGROUP_CODE ) ;

ALTER TABLE SUBGROUP 
    ADD CONSTRAINT SUBGROUP_G_ROUP_FK FOREIGN KEY 
    ( 
     GROUP_CODE
    ) 
    REFERENCES G_ROUP 
    ( 
     GROUP_CODE
    ) 
    NOT DEFERRABLE 
;



-------------
-- MACHINE --
-------------
CREATE TABLE MACHINE 
    ( 
     MACHINE_CODE VARCHAR2 (20)  NOT NULL , 
     MANUFACTURER_CODE VARCHAR2 (10) , 
     MODEL VARCHAR2 (10) , 
     GROUP_CODE VARCHAR2 (10) , 
     SUBGROUP_CODE VARCHAR2 (10) 
    ) 
    LOGGING 
;

ALTER TABLE MACHINE 
    ADD CONSTRAINT MACHINE_PK PRIMARY KEY ( MACHINE_CODE ) ;
 


    
------------------
-- MANUFACTURER --
------------------
CREATE TABLE MANUFACTURER 
    ( 
     CODE VARCHAR2 (10)  NOT NULL , 
     NAME VARCHAR2 (100) 
    ) 
    LOGGING 
;

ALTER TABLE MANUFACTURER 
    ADD CONSTRAINT MANUFACTURER_PK PRIMARY KEY ( CODE ) ;



--------------
-- MATERIAL --
--------------
CREATE TABLE MATERIAL 
    ( 
     CODE VARCHAR2 (40)  NOT NULL , 
     SHORT_DESCRIPTION_EN VARCHAR2 (100) , 
     TYPE VARCHAR2 (10) , 
     UM_CODE VARCHAR2 (10) , 
     PRODUCT_GROUP_CODE VARCHAR2 (50) , 
     MACHINE_CODE VARCHAR2 (20) , 
     MAIN_PART_NUMBER VARCHAR2 (50) 
    ) 
    LOGGING 
;

ALTER TABLE MATERIAL 
    ADD CONSTRAINT MATERIAL_PK PRIMARY KEY ( CODE ) ;

    
    

-------------------
-- PRODUCT GROUP --
-------------------

CREATE TABLE PRODUCT_GROUP 
    ( 
     CODE VARCHAR2 (50)  NOT NULL , 
     CODE_PARENT VARCHAR2 (50) , 
     HIER_LEVEL INTEGER , 
     DESCRIPTION VARCHAR2 (100) 
    ) 
    LOGGING 
;

ALTER TABLE PRODUCT_GROUP 
    ADD CONSTRAINT PRODUCT_GROUP_PK PRIMARY KEY ( CODE ) ;

ALTER TABLE PRODUCT_GROUP 
    ADD CONSTRAINT PRODUCT_GROUP_PRODUCT_GROUP_FK FOREIGN KEY 
    ( 
     CODE_PARENT
    ) 
    REFERENCES PRODUCT_GROUP 
    ( 
     CODE
    ) 
    NOT DEFERRABLE 
;




---------------------
-- UNIT_OF_MEASURE --
---------------------    
CREATE TABLE UNIT_OF_MEASURE 
    ( 
     CODE VARCHAR2 (10)  NOT NULL , 
     TECH_CODE VARCHAR2 (10) , 
     DESCRIPTION VARCHAR2 (50) 
    ) 
    LOGGING 
;

ALTER TABLE UNIT_OF_MEASURE 
    ADD CONSTRAINT UNIT_OF_MEASURE_PK PRIMARY KEY ( CODE ) ;

    
    
    
ALTER TABLE MACHINE 
    ADD CONSTRAINT MACHINE_GROUP_FK FOREIGN KEY 
    ( 
     GROUP_CODE
    ) 
    REFERENCES G_ROUP 
    ( 
     GROUP_CODE
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE MACHINE 
    ADD CONSTRAINT MACHINE_MANUFACTURER_FK FOREIGN KEY 
    ( 
     MANUFACTURER_CODE
    ) 
    REFERENCES MANUFACTURER 
    ( 
     CODE
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE MACHINE 
    ADD CONSTRAINT MACHINE_SUBGROUP_FK FOREIGN KEY 
    ( 
     GROUP_CODE, SUBGROUP_CODE
    ) 
    REFERENCES SUBGROUP 
    ( 
     GROUP_CODE, SUBGROUP_CODE
    ) 
    NOT DEFERRABLE 
;




ALTER TABLE MATERIAL 
    ADD CONSTRAINT MATERIAL_MACHINE_FK FOREIGN KEY 
    ( 
     MACHINE_CODE
    ) 
    REFERENCES MACHINE 
    ( 
     MACHINE_CODE
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE MATERIAL 
    ADD CONSTRAINT MATERIAL_PRODUCT_GROUP_FK FOREIGN KEY 
    ( 
     PRODUCT_GROUP_CODE
    ) 
    REFERENCES PRODUCT_GROUP 
    ( 
     CODE
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE MATERIAL 
    ADD CONSTRAINT MATERIAL_UNIT_OF_MEASURE_FK FOREIGN KEY 
    ( 
     UM_CODE
    ) 
    REFERENCES UNIT_OF_MEASURE 
    ( 
     CODE
    ) 
    NOT DEFERRABLE 
;


----------------
-- V_MATERIAL --
----------------

CREATE OR REPLACE VIEW V_MATERIAL AS
(
SELECT 
	M.CODE, M.SHORT_DESCRIPTION_EN, M.TYPE,
	UM.CODE "UM_CODE", UM.DESCRIPTION "UM_DESCRIPTION",
	PG2.CODE "PRODUCT_GROUP_GF_CODE", PG1.CODE "PRODUCT_GROUP_F_CODE", PG.CODE "PRODUCT_GROUP_CODE", PG.DESCRIPTION "PRODUCT_GROUP_EN",
	M.MACHINE_CODE,
	M.MAIN_PART_NUMBER,
	MAN.CODE "MANUFACTURER CODE", MAN.NAME "MANUFACTURER_NAME",
	G.GROUP_CODE, G.DESCRIPTION_EN "GROUP",
	SG.SUBGROUP_CODE, SG.DESCRIPTION_EN "SUBGROUP"
FROM 
	MATERIAL M, UNIT_OF_MEASURE UM, PRODUCT_GROUP PG, PRODUCT_GROUP PG1, PRODUCT_GROUP PG2, 
	MACHINE MAC, MANUFACTURER MAN, G_ROUP G, SUBGROUP SG
WHERE
	M.UM_CODE = UM.CODE
	AND M.PRODUCT_GROUP_CODE = PG.CODE
	AND PG.CODE_PARENT = PG1.CODE (+)
	AND PG1.CODE_PARENT = PG2.CODE (+)
	AND M.MACHINE_CODE = MAC.MACHINE_CODE
	AND MAC.MANUFACTURER_CODE = MAN.CODE
	AND MAC.GROUP_CODE = G.GROUP_CODE
	AND MAC.GROUP_CODE = SG.GROUP_CODE
	AND MAC.SUBGROUP_CODE = SG.SUBGROUP_CODE
)

